"""Public data contracts shared by API, simulation model and frontend."""

from app.domain.actions import (
    ActionAcceptedMessage,
    ActionErrorDetail,
    ActionRejectedMessage,
    OperatorAction,
    RecordedAction,
    ScenarioActionRequest,
)
from app.domain.ai import (
    AIAnalysisProvenance,
    AIErrorCard,
    AdaptivePlanItem,
    AdaptiveRepetitionPlan,
    AssistantQuestionRequest,
    SessionAIAnalysis,
)
from app.domain.auth import (
    LoginFailureResponse,
    LoginRequest,
    LoginSuccessResponse,
)
from app.domain.base import APIModel, Provenance
from app.domain.enums import (
    ActionType,
    ActionErrorCode,
    AuthRole,
    CompletionReason,
    DiagnosisConclusion,
    DiagnosisReason,
    EquipmentStatus,
    EquipmentType,
    EventSeverity,
    GeneralStatus,
    MeasurementType,
    ParameterOrigin,
    SessionStatus,
    ScenarioOutcome,
    ResultStatus,
    ScenarioRuntimeStatus,
    TrainingMode,
    UserRole,
)
from app.domain.equipment import (
    ComponentState,
    EquipmentDefinition,
    EquipmentParameterDefinition,
)
from app.domain.hints import (
    HintEvidence,
    HintProvenance,
    ScenarioHintMessage,
)
from app.domain.instructor import (
    InstructorAttemptJournal,
    InstructorJournalItem,
    InstructorOverview,
    InstructorTrainee,
    InstructorTraineeList,
)
from app.domain.sessions import (
    AdvanceSessionRequest,
    CreateSessionRequest,
    TrainingSession,
)
from app.domain.results import (
    ResultParameter,
    ResultRemark,
    ScoreSection,
    SessionResult,
    TaskExecutionItem,
    TraineeResultSummary,
    TraineeResultsCollection,
    TraineeResultsPage,
)
from app.domain.scenarios import (
    DiagnosisChoice,
    DiagnosisFormConfig,
    EducationalAssumption,
    EquipmentConnection,
    ScenarioConfig,
    ScenarioSummary,
    SourceReference,
)
from app.domain.signals import ComponentParameterValue, SignalDefinition
from app.domain.telemetry import (
    JournalEntry,
    ModelSnapshot,
    ScenarioTiming,
    ScenarioRuntimeState,
    TelemetryUpdate,
)

__all__ = [
    "APIModel",
    "AIAnalysisProvenance",
    "AIErrorCard",
    "AdaptivePlanItem",
    "AdaptiveRepetitionPlan",
    "AdvanceSessionRequest",
    "ActionAcceptedMessage",
    "ActionErrorDetail",
    "ActionRejectedMessage",
    "ActionType",
    "ActionErrorCode",
    "AuthRole",
    "AssistantQuestionRequest",
    "CompletionReason",
    "CreateSessionRequest",
    "DiagnosisChoice",
    "ComponentParameterValue",
    "ComponentState",
    "EquipmentDefinition",
    "EquipmentConnection",
    "EquipmentParameterDefinition",
    "EquipmentStatus",
    "EquipmentType",
    "EventSeverity",
    "GeneralStatus",
    "HintEvidence",
    "InstructorAttemptJournal",
    "InstructorJournalItem",
    "InstructorOverview",
    "InstructorTrainee",
    "InstructorTraineeList",
    "HintProvenance",
    "DiagnosisConclusion",
    "DiagnosisFormConfig",
    "DiagnosisReason",
    "EducationalAssumption",
    "MeasurementType",
    "JournalEntry",
    "LoginFailureResponse",
    "LoginRequest",
    "LoginSuccessResponse",
    "ModelSnapshot",
    "OperatorAction",
    "RecordedAction",
    "ResultParameter",
    "ResultRemark",
    "ResultStatus",
    "ParameterOrigin",
    "Provenance",
    "ScenarioConfig",
    "ScenarioActionRequest",
    "ScenarioSummary",
    "ScenarioOutcome",
    "ScenarioRuntimeStatus",
    "ScenarioHintMessage",
    "ScoreSection",
    "SessionResult",
    "SessionAIAnalysis",
    "SessionStatus",
    "SignalDefinition",
    "SourceReference",
    "ScenarioTiming",
    "ScenarioRuntimeState",
    "TelemetryUpdate",
    "TaskExecutionItem",
    "TraineeResultSummary",
    "TraineeResultsCollection",
    "TraineeResultsPage",
    "TrainingMode",
    "TrainingSession",
    "UserRole",
]
